#!/bin/bash
set -e

#
# Constants
#

SINCERITY_DIRNAME=${SINCERITY_DIRNAME:-.sincerity}

function join()
{
	local IFS="$1"
	shift
	echo "$*"
}

get-parent-path()
{
	# Finds the parent directory, following symlinks

	local THE_PATH=$1

	set +e
	THE_PATH=$(readlink -f "$THE_PATH" 2> /dev/null)
	if (( "$?" == 0 )); then
		set -e
		dirname "$(readlink -f "$THE_PATH")"
	else
		# "readlink -f" works on Linux, but not on Darwin and OpenSolaris
		set -e
		local OLD_PWD=$PWD
		cd "$(dirname "$THE_PATH")"
		local HERE=$PWD
		cd "$OLD_PWD"
		echo "$HERE"
	fi
}

#
# Find Sincerity home
#

if [ -z "$SINCERITY_HOME" ]; then
	SINCERITY_HOME=$(get-parent-path "$0")
fi

echo "Sincerity home: $SINCERITY_HOME"

#
# Libraries
#

JVM_LIBRARIES=$(echo "$JVM_LIBRARIES" \
"$SINCERITY_HOME/lib"/*.jar)

#
# Run Sincerity
#

JVM_SWITCHES=$(echo "$JVM_SWITCHES" \
-Dfile.encoding=UTF-8 \
-classpath "$(join ":" $JVM_LIBRARIES)")

java $JVM_SWITCHES com.threecrickets.sincerity.Sincerity "$@"
